[IV-22-23] - Objetivo 0
Carlos-SE/App-chores pull request #1
Opened 2022-09-16 08:16 UTC by Carlos-SE

[x] ¿Se trata de un problema real del que se tenga conocimiento personal?
[x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
[x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
[x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

2022-09-16 12:10 UTC, JJ requested changes
Revisa lo que te comento, por favor.

2022-09-16 12:10 UTC, JJ commented on README.md
> +Es una app, que facilita la gestión de las tareas domésticas para grupos.
Estás describiendo una aplicación, no un problema. Tienes que describir un problema.

2022-09-16 12:10 UTC, JJ commented on README.md
> +Permite crear grupos con integrantes, poder crear tareas y adjudicar quien está a cargo de cada una de ellas.
Todo esto ¿para resolver qué problema?

2022-09-16 12:10 UTC, JJ commented on README.md
> +A su vez ofrece estadísticas sobre los grupos y la distribución de tareas.
¿Qué tiene esta aplicación para que esté en la nube y no sea un simple app?

2022-09-16 12:10 UTC, JJ commented on README.md
> +Un cliente puede disfrutar de la aplicación mediante el pago de una mensualidad. Lo que le dará acceso a:
La lógica de negocio no es lo que da dinero, sino qué operación no trivial se va a hacer sobre los datos. Por favor, mira el guión en ese aspecto.

2022-09-16 17:09 UTC, Carlos-SE commented
@JJ Ya he respondido a las preguntas en el README.md de forma que el proyecto queda más claro.
Está listo para revisión.

2022-09-17 10:01 UTC, JJ requested changes
Todavía tendrías que darle alguna vuelta.

2022-09-17 10:01 UTC, JJ commented on README.md
> +Llegados a este punto podemos pensar en la necesidad de que esta solución sea un sistema en la nube ya que nos permite compartir en tiempo real los datos entre varios usuarios, obtener estadísticas d
¿Qué estadísticas? ¿Para qué cliente?

2022-09-17 10:01 UTC, JJ commented on README.md
> +- Historial de tareas
Por favor, recuerda la presentación de ayer y lo que constituye una verdadera lógica de negocio. Nada que sea "buscar, insertar, enviar" lo es.

2022-09-22 10:40 UTC, Carlos-SE commented
@JJ Se ha eliminado la parte que hablaba de la aplicación. Se han especificado tanto los clientes comolas estadísticas y se ha concretado la lógica de negocio.

2022-09-22 15:26 UTC, JJ requested changes
Hacer gráficas no es hacer análisis de datos. Y sigue siendo un problema físico que no se va a resolver porque haya un programa. Hacerlo en la nube es también cuestionable, ya que puede estar en cualquier dispositivo.

2022-09-23 06:57 UTC, Carlos-SE commented
@JJ Se ha cambiado análisis de datos por generación de gráficas. 

Hacerlo en la nube es necesario ya que varios usuarios pueden necesitar editar la misma lista de tareas y poder ver los cambios que realicen los demás compañeros.

Sé que no es una solución al problema, es un apoyo para que el reparto sea más fácil y equilibrado.

2022-09-23 11:13 UTC, JJ commented
> @JJ Se ha cambiado análisis de datos por generación de gráficas.
> 

¿Cómo compruebas que las gráficas están bien, es decir, que la lógica de negocio se ha aplicado correctamente?

> Hacerlo en la nube es necesario ya que varios usuarios pueden necesitar editar la misma lista de tareas y poder ver los cambios que realicen los demás compañeros.
> 
> Sé que no es una solución al problema, es un apoyo para que el reparto sea más fácil y equilibrado.

De veras, no creo que de este contexto puedas sacar un problema. Cualquier cosa que propongas para tratar de cumplir el objetivo acaba por no tener mucho sentido. ¿En serio que crees que mostrando a alguien una gráfica va a hacer las tareas?

Por favor, revisa el guión de este objetivo, sobre todo el tipo de problemas con los cuales podemos tratar y los que no van a dar de si un proyecto suficiente.

2022-09-25 11:26 UTC, Carlos-SE commented
@JJ, He estado dándole vueltas al proyecto y he decidido cambiar totalmente de idea, ya que usted tiene razón y no creo que el proyecto anterior cumpla con las características necesarias para un proyecto de IV.

Esta nueva idea creo que cumple mejor con los requisitos y puede funcionar mejor.

2022-09-25 17:40 UTC, JJ approved these changes
Me parece correcto, pero por favor recuerda que tienes que hacerlo de la forma más real posible: procesar las playlists que te puedas descargar, y usar algoritmos reales de recomendación *que puedas programar tú*

2022-09-26 10:07 UTC, merged