[IV-22-23] Objetivo 5
Carlos-SE/App-chores pull request #59
Opened 2023-02-04 17:54 UTC by Carlos-SE

* [X] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?
* [X] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?
* [X] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [X] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
vez, se va a usar cientos o miles de veces)
* [X] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [X] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?
* [X] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [ ] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?
* [ ] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [ ] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?
* [ ] ¿Se ha abierto un shell en el contenedor y comprobado que los ficheros que
se necesitan están todos incluidos, y que no hay ficheros que no se necesiten?

2023-02-04 19:01 UTC, marcosrmartin commented on Dockerfile
> +CMD ["yarn", "test"]
Échale un vistazo a si el

2023-02-04 19:16 UTC, Carlos-SE commented on Dockerfile
> +CMD ["yarn", "test"]
¿Te refieres a que lo ajuste a /app/test?
Por lo que había leido de documentación de docker, el comando `docker run -t -v `pwd`:/app/test [NombreUsuario]/[Repositorio]` el directorio /app/test es el que se monta localmente. Puede ser que me haya enterado mal al leer la documentación, así que me la volveré a leer y arreglaré los fallos del directorio de trabajo :smiley:

2023-02-04 19:22 UTC, Carlos-SE commented on docs/docker_image.md
> +Tras haber investigado y comprobado pesos y incrementos de estos al instalar cosas necesarias como `Node`, `yarn` y demás paquetes, las imágenes que son más beneficiosas para el proyecto son las ofic
Me documentaré más acerca de esto.
Tengo que ver en qué más se diferencian la última versión de la `lts` y comprobar cuál es más ventajosa.

Muchas gracias por darte cuenta :wink:.

2023-02-04 19:25 UTC, Carlos-SE commented on Dockerfile
> +CMD ["yarn", "test"]
Tienes toda la razón del mundo, lo había entendido al contrario. Lo actualizo inmediatamente!

Muchas gracias! :superhero:

2023-02-04 19:37 UTC, Carlos-SE commented on Dockerfile
> +CMD ["yarn", "test"]
:heavy_check_mark:

2023-02-04 23:06 UTC, marcosrmartin requested changes
Este era el borrado sin querer 🤙

2023-02-04 23:06 UTC, marcosrmartin commented on docs/docker_image.md
> +Para decidir entre estas dos alternativas nos vamos a basar en el mantenimiento que le dan a estas dos opciones, ya que la diferencia de peso tras instalar los paquetes necesarios es muy similar. Ten
* [x] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?

Ojo con la versión, ya que la LTS no es la última versión del lenguaje.

2023-02-04 23:08 UTC, Carlos-SE commented on docs/docker_image.md
> +Para decidir entre estas dos alternativas nos vamos a basar en el mantenimiento que le dan a estas dos opciones, ya que la diferencia de peso tras instalar los paquetes necesarios es muy similar. Ten
Gracias y disculpe las molestias. Es usted todo un caballero 🧐🎩

2023-02-05 11:22 UTC, Carlos-SE commented on docs/docker_image.md
> +Para decidir entre estas dos alternativas nos vamos a basar en el mantenimiento que le dan a estas dos opciones, ya que la diferencia de peso tras instalar los paquetes necesarios es muy similar. Ten
Ya estaría hecho. Muchísimas gracias!

2023-02-05 12:02 UTC, Carlos-SE commented
@marcosrmartin, muchas gracias por tu revisión, cualquier otro error que veas te agradecería que me lo hicieses saber!

2023-02-05 18:03 UTC, marcosrmartin requested changes
Dale una vuelta y lo volvemos a ver.

2023-02-05 18:03 UTC, marcosrmartin commented on docs/docker_image.md
> +### node:lts-bullseye
Recuerda que un criterio es que sea la última versión de Node, por lo que podrías descartar directamente todas las LTS.

2023-02-05 18:13 UTC, Carlos-SE commented on Dockerfile
> +COPY package.json ./
Bien es cierto, que al montarse el volumen en la carpeta con el repositorio esto se puede eliminar. De todas formas lo he puesto para garantizar que si se ejecuta sin haber montado el volumen con los ficheros necesarios este se pueda ejecutar y llevar a cabo los tests.

He supuesto que esto justifica el sentido de añadir este fichero a la construcción.

2023-02-05 18:16 UTC, marcosrmartin commented on Dockerfile
> +COPY package.json ./
Si, pero la única función de la imagen es pasar el test, donde se monta el directorio. Ten en cuenta que en caso de necesitarlo más adelante lo puedes añadir y ya.

2023-02-05 18:21 UTC, Carlos-SE commented on Dockerfile
> +COPY package.json ./
Tienes razón, de esta forma mantenemos lo que es estrictamente necesario.

Muchas gracias por tu aportación :point_right: :point_left:

2023-02-05 19:23 UTC, marcosrmartin approved these changes
👍

2023-02-05 19:23 UTC, marcosrmartin commented on docs/docker_image.md
> +Tras haber investigado y comprobado pesos y incrementos de estos al instalar cosas necesarias como `Node`, `yarn` y demás paquetes, las imágenes que son más beneficiosas para el proyecto son las ofic
typo

2023-02-06 06:30 UTC, Carlos-SE commented
@JJ, le agradecería que le echase un vistazo al PR.

Muchas gracias de antemano😁

2023-02-06 10:07 UTC, JJ commented
> * [x]  ¿Se han establecido criterios previos de elección de la imagen base, así
>       como los criterios de búsqueda que han conducido a las imágenes que se están
>       considerando?
> 
>     * [x]  ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
>       tiene una función específica, tal como testear cómo va nuestra aplicación en la
>       última versión publicada del lenguage?
> 
>     * [x]  ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
> 
>     * [x]  ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
>       irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
>       vez, se va a usar cientos o miles de veces)
> 
>     * [x]  ¿Se han seguido las buenas prácticas en las órdenes que construyen
>       la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
> 
>     * [x]  ¿La imagen incluye sólo y exclusivamente la infraestructura
>       necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
>       "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
>       comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
>       nuestro proyecto?
> 
>     * [x]  ¿Se han documentado y enlazado los commits a las imágenes que se
>       han testeado?

¿Has hecho esto? Si no lo has hecho, ¿por qué lo marcas?

2023-02-06 10:13 UTC, JJ requested changes
Por favor, revisa cuidadosamente el guión para ver qué es lo que se busca en este objetivo.

2023-02-06 10:13 UTC, JJ commented on package.json
> +  "license": "GNU GPLv3",
¿Por qué has cambiado esto? Si es para ver si tira la action, lo mejor hubiera sido que lo cambiaras de versión solo.

2023-02-06 10:13 UTC, JJ commented on docs/docker_image.md
> +### circleci/node
¿No hay más imágenes de desarrolladores verificados?

2023-02-06 10:13 UTC, JJ commented on docs/docker_image.md
> +> Esta opción consiste en utilizar una imágen sin propósito específico, de un sistema operativo en particular dependiendo de la alternativa y sobre este ir añadiendo todas las dependencias necesarias
¿Seguro que lo que hay en la imagen oficial lo necesitas en su totalidad?

2023-02-06 10:13 UTC, JJ commented on Dockerfile
> +COPY yarn.lock ./
¿Seguro que sólo hay que copiar eso?

2023-02-06 10:13 UTC, JJ commented on Dockerfile
> +FROM node:19-bullseye-slim
¿Sólo quieres testear con la versión 19 de node?

2023-02-06 10:13 UTC, JJ commented on Dockerfile
> +COPY lib/ ./lib/
no se copian los fuentes. No estás entendiendo qué es lo que se busca en la imagen.

2023-02-06 10:15 UTC, Carlos-SE commented on package.json
> +  "license": "GNU GPLv3",
Porque saltaba un warning indicando que estaba mal escrito

2023-02-06 10:19 UTC, JJ commented on package.json
> +  "license": "GNU GPLv3",
¿Dónde?
En todo caso, si no es de este objetivo, hacedlo tras crear un issue en otro PR diferente.

2023-02-06 10:30 UTC, Carlos-SE commented on package.json
> +  "license": "GNU GPLv3",
Al iniciar el Docker.
De acuerdo, gracias por decírmelo :smiley:

2023-02-06 10:34 UTC, Carlos-SE commented on Dockerfile
> +FROM node:19-bullseye-slim
> - [X]  ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?

Se ha hecho para la última versión de node por este check. Antes tenía puesto la versión `lts` pero va con node 18

2023-02-06 10:35 UTC, Carlos-SE commented on Dockerfile
> +COPY lib/ ./lib/
Tiene sentido, no es necesario. ¡Muchas gracias!

2023-02-06 10:39 UTC, Carlos-SE commented on docs/docker_image.md
> +### circleci/node
Por supuesto que las hay, pero de todas las que he visto con el filtro de [desarrolladores verificados](https://hub.docker.com/search?q=node&image_filter=store) incluyen demasiadas cosas y esto hace que el peso aumente considerablemente. Está puesto en un comentario justo debajo, de todas maneras añadiré más opciones

2023-02-06 10:45 UTC, Carlos-SE commented on docs/docker_image.md
> +> Esta opción consiste en utilizar una imágen sin propósito específico, de un sistema operativo en particular dependiendo de la alternativa y sobre este ir añadiendo todas las dependencias necesarias
Estoy seguro de que no, ya que `wget` y `curl` no se usan y se descargan por la imagen oficial. Esto me abre a dos posibilidades, eliminar esos paquetes de la imagen oficial o construir la imagen al igual que hace el equipo de de node, basándome en una imagen `bare-bone` pero instalando nada más los paquetes necesarios.

2023-02-06 11:26 UTC, JJ commented on Dockerfile
> +FROM node:19-bullseye-slim
Por favor, mira la especificación del objetivo y lo que dice. Es una imagen para test. Es raro que quieras testear con la misma versión de un lenguaje, *siempre la misma*.

2023-02-06 11:27 UTC, Carlos-SE commented on Dockerfile
> +FROM node:19-bullseye-slim
Claro, tendría que ajustarme según vayan actualizando

2023-02-06 11:31 UTC, Carlos-SE commented on Dockerfile
> +FROM node:19-bullseye-slim
He visto que está la etiqueda current, que la van actualizando a la última versión que estén gestionando

2023-02-06 11:32 UTC, Carlos-SE commented on Dockerfile
> +FROM node:19-bullseye-slim
Sino, está la alternativa `lts`, que no está con node 19, pero van a mantener actualizando y con soporte en un periodo prolongado de tiempo

2023-02-06 19:59 UTC, Carlos-SE commented
@JJ, he tenido en cuenta todo lo que me ha comentado, la diferencia entre montar la imagen desde una `bare-bone` o no es más grande de lo que había comprobado, ya que he probado con versiones imágenes más ligeras en lugar de cogar unas que faciliten más las tareas.

Le agradecería una revisión.

@marcosrmartin si ves algo nuevo que añadir también te lo agradezco.

Muchas gracias de antemano :smile:

2023-02-07 07:22 UTC, JJ requested changes
Por favor, consulta las mejores prácticas y los comentarios que se te han hecho.

2023-02-07 07:22 UTC, JJ commented on Dockerfile
> +COPY yarn.lock ./
¿Por qué usas dos sentencias cuando podrías usar una sola?

2023-02-07 07:22 UTC, JJ commented on Dockerfile
> +RUN yarn install
¿Con qué privilegios estás ejecutando esto?

2023-02-07 07:22 UTC, JJ commented on Dockerfile
> +    && apk add curl nodejs yarn
¿Dónde usas curl?

2023-02-07 07:22 UTC, JJ commented on package.json
> +  "license": "GNU GPLv3",
No parece que esté mejor escrito, de todas formas.

2023-02-07 09:26 UTC, Carlos-SE commented on Dockerfile
> +RUN yarn install
Se me olvidó volver a poner USER 1001 :upside_down_face:

2023-02-07 09:27 UTC, Carlos-SE commented on Dockerfile
> +    && apk add curl nodejs yarn
con esta alternativa no, cuando estuve con debian:bullseye-slim si y se me olvidó quitarlo...

2023-02-07 09:27 UTC, JJ commented on Dockerfile
> +RUN yarn install
También ponerle al usuario un nombre.

2023-02-07 09:40 UTC, Carlos-SE commented
@JJ, gracias por sus comentarios, tuve un par de despistes ayer al hacer cambios. Le agradecería una revisión.

Muchas gracias de antemano :smiley:

2023-02-07 10:51 UTC, JJ approved these changes
Voy a darlo por bueno, pero es totalmente innecesario que asignéis un UID específico al usuario.

2023-02-07 10:51 UTC, JJ commented on Dockerfile
> +RUN adduser -u 1001 -D node &&\
¿Por qué usas 1001 como UID?

2023-02-07 10:58 UTC, merged

2024-03-03 17:18 UTC, Gdakgdak22 approved these changes